In [ ]:
#HANDLING AND DATE AND TIME

In [1]:
import numpy as np 
import pandas as pd 

date= pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')
print(date.head())
print(time.head())

   order_id  user_id  r_id  amount        date  partner_id  delivery_time  \
0      1001        1     1     550  2022-05-10           1             25
1      1002        1     2     415  2022-05-26           1             19
2      1003        1     3     240  2022-06-15           5             29
3      1004        1     3     240  2022-06-29           4             42
4      1005        1     3     220  2022-07-10           1             58

   delivery_rating  restaurant_rating
0                5                3.0
1                5                2.0
2                4                NaN
3                3                5.0
4                1                4.0
                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [2]:
print(date.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           25 non-null     int64
 1   user_id            25 non-null     int64
 2   r_id               25 non-null     int64
 3   amount             25 non-null     int64
 4   date               25 non-null     object
 5   partner_id         25 non-null     int64
 6   delivery_time      25 non-null     int64
 7   delivery_rating    25 non-null     int64
 8   restaurant_rating  17 non-null     float64
dtypes: float64(1), int64(7), object(1)
memory usage: 1.9+ KB
None

In [3]:
print(time.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB
None

#WORKING WITH DATES

In [ ]:
#CONVERTING TO DATETIME DATATYPES

In [4]:
date['date']=pd.to_datetime(date['date'])
print(date.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           25 non-null     int64
 1   user_id            25 non-null     int64
 2   r_id               25 non-null     int64
 3   amount             25 non-null     int64
 4   date               25 non-null     datetime64[ns]
 5   partner_id         25 non-null     int64
 6   delivery_time      25 non-null     int64
 7   delivery_rating    25 non-null     int64
 8   restaurant_rating  17 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(7)
memory usage: 1.9 KB
None

In [ ]:
#1.EXTRACT YEAR

In [5]:
date['date_year'] = date['date'].dt.year

date.sample(5)

,order_id,user_id,r_id,amount,date,partner_id,delivery_time,delivery_rating,restaurant_rating,date_year
23,1024,5,2,645,2022-07-21,2,58,2,1.0,2022
16,1017,4,4,300,2022-05-30,1,50,1,NaN,2022
11,1012,3,4,180,2022-05-20,5,33,4,1.0,2022
12,1013,3,2,230,2022-05-30,4,45,3,NaN,2022
1,1002,1,2,415,2022-05-26,1,19,5,2.0,2022

In [ ]:
#2.EXTRACT MONTH

In [8]:
date['date_month_no']=date['date'].dt.month
print(date.head())

   order_id  user_id  r_id  amount       date  partner_id  delivery_time  \
0      1001        1     1     550 2022-05-10           1             25
1      1002        1     2     415 2022-05-26           1             19
2      1003        1     3     240 2022-06-15           5             29
3      1004        1     3     240 2022-06-29           4             42
4      1005        1     3     220 2022-07-10           1             58

   delivery_rating  restaurant_rating  date_year  date_month_no
0                5                3.0       2022              5
1                5                2.0       2022              5
2                4                NaN       2022              6
3                3                5.0       2022              6
4                1                4.0       2022              7

In [9]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,order_id,user_id,r_id,amount,date,partner_id,delivery_time,delivery_rating,restaurant_rating,date_year,date_month_no,date_month_name
0,1001,1,1,550,2022-05-10,1,25,5,3.0,2022,5,May
1,1002,1,2,415,2022-05-26,1,19,5,2.0,2022,5,May
2,1003,1,3,240,2022-06-15,5,29,4,NaN,2022,6,June
3,1004,1,3,240,2022-06-29,4,42,3,5.0,2022,6,June
4,1005,1,3,220,2022-07-10,1,58,1,4.0,2022,7,July

In [ ]:
#3.EXTRACT DAYS

In [10]:
date['date_day'] = date['date'].dt.day

date.head()

,order_id,user_id,r_id,amount,date,partner_id,delivery_time,delivery_rating,restaurant_rating,date_year,date_month_no,date_month_name,date_day
0,1001,1,1,550,2022-05-10,1,25,5,3.0,2022,5,May,10
1,1002,1,2,415,2022-05-26,1,19,5,2.0,2022,5,May,26
2,1003,1,3,240,2022-06-15,5,29,4,NaN,2022,6,June,15
3,1004,1,3,240,2022-06-29,4,42,3,5.0,2022,6,June,29
4,1005,1,3,220,2022-07-10,1,58,1,4.0,2022,7,July,10

In [ ]:
#DAY OF WEEK

In [11]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,order_id,user_id,r_id,amount,date,partner_id,delivery_time,delivery_rating,restaurant_rating,date_year,date_month_no,date_month_name,date_day,date_dow
0,1001,1,1,550,2022-05-10,1,25,5,3.0,2022,5,May,10,1
1,1002,1,2,415,2022-05-26,1,19,5,2.0,2022,5,May,26,3
2,1003,1,3,240,2022-06-15,5,29,4,NaN,2022,6,June,15,2
3,1004,1,3,240,2022-06-29,4,42,3,5.0,2022,6,June,29,2
4,1005,1,3,220,2022-07-10,1,58,1,4.0,2022,7,July,10,6

In [ ]:
#day of week-name

In [15]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['partner_id','order_id','amount']).head()

,user_id,r_id,date,delivery_time,delivery_rating,restaurant_rating,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,1,1,2022-05-10,25,5,3.0,2022,5,May,10,1,Tuesday
1,1,2,2022-05-26,19,5,2.0,2022,5,May,26,3,Thursday
2,1,3,2022-06-15,29,4,NaN,2022,6,June,15,2,Wednesday
3,1,3,2022-06-29,42,3,5.0,2022,6,June,29,2,Wednesday
4,1,3,2022-07-10,58,1,4.0,2022,7,July,10,6,Sunday

In [ ]:
#is weekend?

In [16]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['partner_id','order_id','amount']).head()

,user_id,r_id,date,delivery_time,delivery_rating,restaurant_rating,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,1,1,2022-05-10,25,5,3.0,2022,5,May,10,1,Tuesday,0
1,1,2,2022-05-26,19,5,2.0,2022,5,May,26,3,Thursday,0
2,1,3,2022-06-15,29,4,NaN,2022,6,June,15,2,Wednesday,0
3,1,3,2022-06-29,42,3,5.0,2022,6,June,29,2,Wednesday,0
4,1,3,2022-07-10,58,1,4.0,2022,7,July,10,6,Sunday,1

In [ ]:
#EXTRACT TIME ELAPSED BETWEEN DATES

In [17]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 11, 22, 12, 25, 33, 284802)

In [18]:
today - date['date']

0    1292 days 12:25:33.284802
1    1276 days 12:25:33.284802
2    1256 days 12:25:33.284802
3    1242 days 12:25:33.284802
4    1231 days 12:25:33.284802
5    1261 days 12:25:33.284802
6    1248 days 12:25:33.284802
7    1234 days 12:25:33.284802
8    1224 days 12:25:33.284802
9    1210 days 12:25:33.284802
10   1292 days 12:25:33.284802
11   1282 days 12:25:33.284802
12   1272 days 12:25:33.284802
13   1260 days 12:25:33.284802
14   1249 days 12:25:33.284802
15   1287 days 12:25:33.284802
16   1272 days 12:25:33.284802
17   1256 days 12:25:33.284802
18   1241 days 12:25:33.284802
19   1226 days 12:25:33.284802
20   1240 days 12:25:33.284802
21   1233 days 12:25:33.284802
22   1226 days 12:25:33.284802
23   1220 days 12:25:33.284802
24   1213 days 12:25:33.284802
Name: date, dtype: timedelta64[ns]

In [19]:
(today - date['date']).dt.days

0     1292
1     1276
2     1256
3     1242
4     1231
5     1261
6     1248
7     1234
8     1224
9     1210
10    1292
11    1282
12    1272
13    1260
14    1249
15    1287
16    1272
17    1256
18    1241
19    1226
20    1240
21    1233
22    1226
23    1220
24    1213
Name: date, dtype: int64

In [ ]:
#MONTH PASSED

In [21]:
np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0     1861226.0
1     1838186.0
2     1809386.0
3     1789226.0
4     1773386.0
5     1816586.0
6     1797866.0
7     1777706.0
8     1763306.0
9     1743146.0
10    1861226.0
11    1846826.0
12    1832426.0
13    1815146.0
14    1799306.0
15    1854026.0
16    1832426.0
17    1809386.0
18    1787786.0
19    1766186.0
20    1786346.0
21    1776266.0
22    1766186.0
23    1757546.0
24    1747466.0
Name: date, dtype: float64

In [ ]:
#CONVERTING TO DATETIME DATATYPES

In [22]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [23]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [ ]:
#EXTRACT TIME PART

In [24]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
#TIME-DIFFERENCE

In [25]:
today - time['date']

0     4360 days 11:35:33.284802
1     4224 days 12:45:33.284802
2     4710 days 12:04:33.284802
3     4012 days 11:54:33.284802
4     4409 days 13:14:33.284802
                 ...
995   4999 days 11:35:33.284802
996   4320 days 13:11:33.284802
997   4785 days 12:48:33.284802
998   4901 days 12:51:33.284802
999   4173 days 13:00:33.284802
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# IN SECONDS

In [26]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.767457e+08
1      3.649995e+08
2      4.069875e+08
3      3.466797e+08
4      3.809853e+08
           ...
995    4.319553e+08
996    3.732955e+08
997    4.134701e+08
998    4.234927e+08
999    3.605940e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
# IN MINUTES

In [27]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.279096e+06
1      6.083326e+06
2      6.783125e+06
3      5.777995e+06
4      6.349755e+06
           ...
995    7.199256e+06
996    6.221592e+06
997    6.891169e+06
998    7.058212e+06
999    6.009901e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
#IN HOURS

In [28]:
(today - time['date'])/np.timedelta64(1,'h')

0      104651.592579
1      101388.759246
2      113052.075912
3       96299.909246
4      105829.242579
           ...
995    119987.592579
996    103693.192579
997    114852.809246
998    117636.859246
999    100165.009246
Name: date, Length: 1000, dtype: float64